# Generated by Django 4.1.4 on 2023-10-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
