# Generated by Django 4.1.4 on 2023-10-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_delete_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='start_price',
            new_name='price',
        ),
    ]
