# Generated by Django 4.1.4 on 2023-10-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-price']},
        ),
    ]
