# Generated by Django 4.1.4 on 2023-10-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0006_alter_auction_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-pk']},
        ),
    ]
